### ISSUE TITLE
链接mysql数据报错

### ISSUE THREAD

**Issue by momodiy** [chenshenhai/koa2-note#42]
### 背景
我已经安装好了mysql(MAC)并配置了全局变量，并使用idea内置的mysql连接工具中连接成功。
![connection image](https://github.com/momodiy/koa2-note/blob/master/demo/upload-async/static/image/steven/933f32b84c97d.png?raw=true)

### 连接代码
```
let store = new MysqlSession({ 
    user: 'root',
    password: '12345678',
    database: 'test',
    host: '127.0.0.1',
    port: 3306,
    insecureAuth: true
})
```

### 错误信息

```
(node:2837) UnhandledPromiseRejectionWarning: Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Handshake.Sequence._packetToError (/Users/stevenlee/github/test/koa2-note/demo/mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Handshake.ErrorPacket (/Users/stevenlee/github/test/koa2-note/demo/mysql/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)
    at Protocol._parsePacket (/Users/stevenlee/github/test/koa2-note/demo/mysql/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/stevenlee/github/test/koa2-note/demo/mysql/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/stevenlee/github/test/koa2-note/demo/mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/stevenlee/github/test/koa2-note/demo/mysql/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------

```
在`session`、`mysql`两个模块下连接mysql都遇到了这个问题，使用的node包分别为`koa-mysql-session`与`mysql`.

上网查了好久都没解决，如果哪位大神有什么好的思路，跪求分享，不胜感激:ambulance:

**Comment by wendesun** [comment]
我也是同样的问题

**Comment by ddshiyu** [comment]
https://waylau.com/node.js-mysql-client-does-not-support-authentication-protocol/

**Comment by jokereven** [comment]
https://waylau.com/node.js-mysql-client-does-not-support-authentication-protocol/
order by ddshiyu's method.

**Comment by JuanJuanZhang123** [comment]
这是来自QQ邮箱的假期自动回复邮件。
你好，我是张娟娟，邮件已经收到，我会尽快给与答复
