### ISSUE TITLE
系列文章写得真好，不过在服务器上面运行demo project时出现问题

### ISSUE THREAD

**Issue by nihaoit** [chenshenhai/koa2-note#8]
我把demo/project里面的代码放在服务上面跑，配置完成后，执行
```shell
npm run start_server
```
出现如下错误

```shell
module.js:472
    throw err;
    ^

Error: Cannot find module './../models/user-info'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/koa2-note/demo/project/server/services/user-info.js:6:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/koa2-note/demo/project/server/controllers/user-info.js:1:87)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by chenshenhai** [comment]
@nihaoit 您好，请问你是在 demo/project目录下直接执行 `npm run start_server` 的么?

**Comment by chenshenhai** [comment]
@nihaoit 我重新把项目clone下来启动demo/project的`npm run start_server`命令，没发现问题，请问你是怎么操作才出现的问题？？

**Comment by nihaoit** [comment]
@chenshenhai ,感谢您这么及时的回复，我通过如下的修改解决了：
把project/server/models/user-Info.js（Info的首字母是大写的），修改成project/server/models/user-info.js就可以成功运行了。
我的系统是Ubuntu server 16.04
再次感谢您这么好的分享，^_^
